### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by aertist** [westgarthb/style-transfer-video-processor#1]
`Traceback (most recent call last):
  File "style_frames.py", line 112, in <module>
    sf.get_style_info()
  File "style_frames.py", line 57, in get_style_info
    self.t_const = np.ceil(frame_length / (ref_count - 1))
ZeroDivisionError: division by zero`

I'm a newbie. Can you please make readme a lil bit easy to read for a newbie. 😅 
Great repo btw. I'm using only one style image.
Here is the [colab](https://colab.research.google.com/drive/1fJwXaJqqfXlODFajXwmojc0mFb3RlHnq?usp=sharing) you can replicate this or can add this to the repo as well.

My config.py looks like this:
```INPUT_FPS = 30
    INPUT_VIDEO_NAME = 'input.mp4'
    INPUT_VIDEO_PATH = f'{ROOT_PATH}/{INPUT_VIDEO_NAME}'
    INPUT_FRAME_DIRECTORY = f'{ROOT_PATH}/input_frames'
    INPUT_FRAME_FILE = '{:0>4d}_frame.png'
    INPUT_FRAME_PATH = f'{INPUT_FRAME_DIRECTORY}/{INPUT_FRAME_FILE}'

    STYLE_REF_DIRECTORY = f'{ROOT_PATH}/style_ref'
    # defines the reference style image transition sequence. Values correspond to indices in STYLE_REF_DIRECTORY
    STYLE_SEQUENCE = [1]

    OUTPUT_FPS = 30
    OUTPUT_VIDEO_NAME = 'output_video.mp4'
    OUTPUT_VIDEO_PATH = f'{ROOT_PATH}/{OUTPUT_VIDEO_NAME}'
    OUTPUT_FRAME_DIRECTORY = f'{ROOT_PATH}/output_frames'
    OUTPUT_FRAME_FILE = '{:0>4d}_frame.png'
    OUTPUT_FRAME_PATH = f'{OUTPUT_FRAME_DIRECTORY}/{OUTPUT_FRAME_FILE}'

    GHOST_FRAME_TRANSPARENCY = 0.1`

Also this error too:

`Traceback (most recent call last):
  File "style_frames.py", line 114, in <module>
    sf.get_output_frames()
  File "style_frames.py", line 84, in get_output_frames
    blended_img = prev_style + next_style
ValueError: operands could not be broadcast together with shapes (1138,1707,3) (1138,1713,3) `

**Comment by westgarthb** [comment]
I just pushed some bug fixes to the repo that should solve both errors.  Let us know if you can get it to work! Great job on the colab notebook, we'll look into adding something similar to the repo
